### ISSUE TITLE
[Question] Is there a working (staging) temporary website until the product is ready?

### ISSUE THREAD

**Issue by shunkakinoki** [Nakajima-Foundation/ownplate#518]
I just came across this project and seems really great!
The commission from the food delivery startups is really high and is a serious problem (close to 20~30% I suppose?)
If there is an open-source powered food-delivery system that powers the same if not more capabilities that would seriously be a game-changer, and I really appreciate your work.

My question is that will there be a temporary website for the project, albeit a simple project demo site or the current work-in-progress site to showcase the project? If people can have access to the current status of the project even if it is not completed, (and it's really cheap to do so through firebase hosting, vercel, or netlify), I personally think it will really be a huge boost.

**Comment by snakajima** [comment]
I appreciate your feedback. We have a beta services available for both US market and Japanese market. Please take a look. 

US: https://ownplate.today/
Japan: https://omochikaeri.com/

**Comment by shunkakinoki** [comment]
That's really awesome!
(And sorry for not knowing)
Do you have plans to list it on the project description if possible?
